@startuml

!include data.pu
!include access.pu
!include services.pu

ProfileService "1" --> "1" UserParameters
ProfileService "*" --> "1" UserParametersRepo

AccountService "1" --> "1" Key
AccountService "*" --> "1" KeyRepo


TransactionsService "1" --> "*" Transaction
TransactionsService "*" --> "1" TransactionAccess
TransactionAccess "1" --> "1" TransactionRepo

RegistryService "1" --> "*" Identity
RegistryService "1" --> "*" Certification
RegistryService "*" --> "1" IdentitiesAccess
IdentitiesAccess "1" --> "1" IdentitiesRepo
RegistryService "*" --> "1" CertificationAccess
CertificationAccess "1" --> "1" CertificationRepo

NetworkService "1" --> "*" Node
NetworkService "*" --> "1" NodeRepo

BlockchainService "1" --> "1" Blockchain
BlockchainService "1" --> "1" Community
BlockchainService "*" --> "1" BlockchainAccess
BlockchainAccess "1" --> "1" BlockchainRepo
BlockchainService "*" --> "1" CommunityAccess
CommunityAccess "1" --> "1" CommunityRepo

package API {
    class BMAAccess << (S,cyan) >>  {
        get()
        post()
        broadcast()
    }
}

BlockchainAccess --> BMAAccess
CommunityAccess --> BMAAccess
TransactionAccess --> BMAAccess
IdentitiesAccess --> BMAAccess
CertificationAccess --> BMAAccess

@enduml