@startuml

!include core-classes.pu
!include gui-classes.pu
!include models-classes.pu
!include api.pu

MainWindow "1" --> "1" App

CertificationDialog --> Community
TransferDialog --> Community

CurrencyTab "1" --> "1" Community

CommunityTab -right-> IdentitiesFilterProxyModel
NetworkTab -right-> NetworkFilterProxyModel
WalletTab -right-> WalletsFilterProxyModel

WalletsFilterProxyModel -up-> Wallet
NetworkFilterProxyModel -up-> Network
TxHistoryFilterProxyModel -up-> Transfer

ConfigureAccountDialog --> CommunitiesListModel
ConfigureCommunityDialog --> RootNodesTableModel

ConfigureAccountDialog --> Account
ConfigureCommunityDialog --> Community

Account ..> BMADataAccess
Community ..> BMADataAccess
Wallet ..> BMADataAccess
Transfer ..> BMADataAccess
Identity ..> BMADataAccess
BMADataAccess .left.> Network

@enduml