@startuml


package gui {
		class MainWindow {
		}
		MainWindow "1" --* "1" CommunityView

		class CommunityView {
		}
		CommunityView "1" --* "1" WalletTab
		CommunityView "1" -down-* "1" InformationsTab
		CommunityView "1" --* "1" TransactionsTab
		CommunityView "1" --* "1" IdentitiesTab
		CommunityView "1" --* "1" WotTab
		CommunityView "1" -down-* "1" NetworkTab


		class WalletTab {
		}

		class InformationsTab {
		}

		class TransactionsTab {
		}

		class NetworkTab {
		}

		class IdentitiesTab {
		}

		class WotTab {
		}
		package dialogs {
		class CertificationDialog
		class TransferDialog
		class ContactDialog
		class ConfigureAccountDialog
		class ConfigureCommunityDialog
		}

	MainWindow --> CertificationDialog
	MainWindow --> TransferDialog
	MainWindow --> ContactDialog
	MainWindow --> ConfigureAccountDialog
	ConfigureAccountDialog --> ConfigureCommunityDialog
}
@enduml
