@startuml



class ProfileService << (S,cyan) >>  {
    add_connection()
    remove_connection()

}

class AccountService << (S,cyan) >>  {
    send_transaction()
    send_certification()
    send_membership()
    send_identity()
    send_revokation()
}
class TransactionsService << (S,cyan) >>  {
    refresh_transactions()
    rollback_transactions()
}

class RegistryService << (S,cyan) >> {
    get_identity()
    get_certifiers_of()
    get_certified_by()
}

class NetworkService << (S,cyan) >>  {
    discover_network()
}

class BlockchainService  << (S,cyan) >>  {
    receive_block()
}

@enduml